services:
  - type: web
    name: gdrive-seemore
    env: python
    plan: starter
    buildCommand: poetry install --no-root
    #startCommand: gunicorn app:app --chdir ./provider
    startCommand: poetry run flask --app provider --debug run --port 5000
    autoDeploy: false